image: docker:latest

services:
  - docker:dind

# Docker Cloud Variables
# Note: to use the Gitlab CI Registry, delete the variables from the CI settings.
# `echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin`
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  - apk add --no-cache bash

# Base and CI Images
# One Base Image to Rule them All
build-base-ci:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - docker build -f ./src/Dockerfiles/Base.Dockerfile -t $CI_REGISTRY_IMAGE/base .
    - docker login docker.io
    - docker push $IMAGE_TAG/base
  only:
    - master

build-lemp-7.4:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
    PHP_VERSIONS: "7.4"
  script:
    - docker login docker.io
    - ./build-ci.sh
  only:
    - master

build-lemp-7.3:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
    PHP_VERSIONS: "7.3"
  script:
    - docker login docker.io
    - ./build-ci.sh
  only:
    - master

build-all-versions:
  when: manual
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
    PHP_VERSIONS: "7.4 7.3 7.2 7.1 7.0 5.6"
  script:
    - docker login docker.io
    - ./build-ci.sh
  only:
    - master

build-node:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - docker build -f ./Dockerfiles/Node.Dockerfile -t $CI_REGISTRY_IMAGE/node .
    - docker login docker.io
    - docker push $IMAGE_TAG/node
  only:
    - master