name: build-php

on:
  push:
    branches:
      - "master"
      - "**"

jobs:
  build-php-images:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: [81, 80, 74]

    name: Build PHP ${{ matrix.php }}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src/php${{ matrix.php }}
          file: ./src/php${{ matrix.php }}/Dockerfile
          push: true
          tags: robmellett/php-${{ matrix.php }}:latest
          build-args: |
            WWWGROUP=1000
