name: build-php

on:
  push:
    branches:
      - "master"

  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-php-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [84, 83, 82, 81]

    name: Build PHP ${{ matrix.php }}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./src/php${{ matrix.php }}
          file: ./src/php${{ matrix.php }}/Dockerfile
          push: true
          tags: robmellett/php-${{ matrix.php }}:latest,${{ steps.meta.outputs.tags }}
          build-args: |
            WWWGROUP=1000
            WWWUSER=1000
