name: build-php-ci

on:
  push:
    branches:
      - "master"

  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-php-ci-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [85, 84]

    name: Build PHP ${{ matrix.php }} CI

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          context: ./src/php${{ matrix.php }}-ci
          file: ./src/php${{ matrix.php }}-ci/Dockerfile
          push: true
          tags: robmellett/php-${{ matrix.php }}-ci:latest
