name: Run Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        image: ["base", "php84", "php85", "php85-cli"]

    name: Build Containers [${{ matrix.image }}]

    steps:
      - name: Check Out Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Build
        id: docker_build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: ./src/${{ matrix.image }}
          file: ./src/${{ matrix.image }}/Dockerfile
          tags: robmellett/${{ matrix.image }}:test
          build-args: |
            WWWGROUP=1000
            WWWUSER=1000
